### ISSUE TITLE
The frill part of walls and windows are fullbright if they are over space.

### ISSUE THREAD

**Issue by tralezab** [wall-nerds/wallening#78]
![image](https://user-images.githubusercontent.com/40974010/167964893-026e8885-6e33-403c-b078-5cdca966f84f.png)

On the left, it makes sense. Brightness on inside the station, dark. On the top, it doesn't because the frills are fully lit but the rest of the window/wall isn't.

**Comment by LemonInTheDark** [comment]
I know how to fix this for walls, we basically just make the frill plane mask the lighting plane, and then mask the frill plane with anything that sits "on top" of it (if that becomes a problem)
Windows is a bit more tricky, since they should actually show the light. The issue here is that space light doesn't really propogate enough for it to look right. That requires larger changes tho, so I've not done anything about it yet. Been meaning to tho

**Comment by LemonInTheDark** [comment]
![image](https://github.com/wall-nerds/wallening/assets/58055496/3135920a-05a4-4535-bcdd-7fc348ab0467)
Handled, at least partly. Some work I did upstream roughly dealt with the "unevenness" problem
Something's wrong with edges though. Need to figure that out

**Comment by LemonInTheDark** [comment]
This is fixed, the above is because the cutter map has fullbright applied to its areas, which does not play well with well, turf lighting.
